### ISSUE TITLE
notifications facebook style

### ISSUE THREAD

**Issue by amiresfahani** [pomozoff/caspianphone#112]
![2d476d26b01f347d3b4a5274f3ed3822e14f811bacbd81695bd851dbf2a8b5a9](https://cloud.githubusercontent.com/assets/8526958/6200550/7d8fd16c-b492-11e4-8902-438cbdc40596.jpg)

if possible please change the notifications area for incoming message 

One Call Caspian
username or number: message

**Comment by pomozoff** [comment]
Done
