### ISSUE TITLE
settings page starting from middle

### ISSUE THREAD

**Issue by amiresfahani** [pomozoff/caspianphone#123]
settings screen loads from middle of the page

**Comment by pomozoff** [comment]
Please, give me the screenshots of this glitch. I can't reproduce it on my device.

**Comment by amiresfahani** [comment]
![545a555dcd3626f88d68072e9f625fa4250b6f35e3d8b22974e7d8836fb64141](https://cloud.githubusercontent.com/assets/8526958/6655785/13603fe2-cb22-11e4-8da7-c468e66e9b63.jpg)

**Comment by amiresfahani** [comment]
https://onecallcaspian.co.uk/MOV00363.mp4

**Comment by pomozoff** [comment]
I asked about wrong text ringtone.
I know about wrong settings behavior.
