### ISSUE TITLE
One Call Caspian beta expired!

### ISSUE THREAD

**Issue by amiresfahani** [pomozoff/caspianphone#185]
![5ce1068977547b084a0ccb620a459bf3e6a99332a5c04694182b266f51c90179](https://cloud.githubusercontent.com/assets/8526958/9909969/9bebac0a-5c92-11e5-81fa-bdb01294a6c9.jpg)

**Comment by pomozoff** [comment]
Do you need a new beta release?
They are all expired in 30 days after release.

**Comment by amiresfahani** [comment]
thought it is issue with apple store version, please ignore, no new test build needed
