### ISSUE TITLE
incoming call notification

### ISSUE THREAD

**Issue by amiresfahani** [pomozoff/caspianphone#96]
wrong text should be incoming number only

![81b229e0fa98816b91871385f3f4550d8a09e779c5664d3e192ec84ab7cf61f1](https://cloud.githubusercontent.com/assets/8526958/5341157/ff3ffeae-7f08-11e4-9511-dae55141fab8.jpg)

**Comment by pomozoff** [comment]
Can't reproduce, may be already fixed. Need to check it.
