### ISSUE TITLE
chat history duplicate records

### ISSUE THREAD

**Issue by amiresfahani** [pomozoff/caspianphone#97]
![8f185d349395a5ca80b069cc25896ab7ec91da154b993b1133875dbe325cd3d5](https://cloud.githubusercontent.com/assets/8526958/5341189/1eef8378-7f09-11e4-8f03-d2b50dd032e8.jpg)

**Comment by pomozoff** [comment]
I think we can fix it only after we shall switch chat's store implementation from file to CoreData

**Comment by pomozoff** [comment]
Fixed
