### ISSUE TITLE
chat history some items without delete button

### ISSUE THREAD

**Issue by amiresfahani** [pomozoff/caspianphone#98]
![d23f223945cbed8160fa0528e520a34369135c49b34237a9018cbbaf3e4be3cd](https://cloud.githubusercontent.com/assets/8526958/5341235/6654e424-7f09-11e4-82a9-55065a1a30b0.jpg)
![ebcc884dd2ab446da937422284dd6877610fb7f86769827bcbc0a48e7dc2d88b](https://cloud.githubusercontent.com/assets/8526958/5341236/665aed38-7f09-11e4-902e-dbd56f471fbe.jpg)

**Comment by pomozoff** [comment]
Looks like these contacts have similar phone number. That's why you can not delete the second line.
I'm going to add additional compare to contact's name to detect that it is a Support Contact.
